- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - block:
    - name: "list files in ssh_keys dir"
      shell: "ls -lrt | grep -v total | awk {'print $NF'}"
      register: keys_list

    - set_fact:
        ssh_keys: "keys_list.stdout_lines"  

    - name: "set 0600 permissions"
      file:
        path: "ssh_keys/{{ item }}"
        mode: '0600'
      with_items: "{{ ssh_keys }}"

    delegate_to: localhost

  - name: "collect facts"
    setup:
    register: results

  - debug: var=results
