- hosts: localhost
  become: false
  gather_facts: no
  connection: local
  vars_files: 
    - vars/main.yml
  tasks:
  - name: "create ssh keys files"
    copy:
      dest: ssh_keys/oem-il-iaas-keypair-test.pem
      content: "{{ test_env_ssh_key }}"
      mode: 0600
          #  - name: "change permissions for ssh keys"
          #    block:
          #    - name: "list files in ssh_keys dir"
          #      shell: "ls -lrt ssh_keys/ | grep -v total | awk {'print $NF'}"
          #      register: keys_list
          #    - debug: var=keys_list
          #    - set_fact:
          #        ssh_keys: "{{ keys_list.stdout_lines }}"
          #    - name: "set 0600 permissions"
          #      file:
          #        path: "ssh_keys/{{ item }}"
          #        mode: '0600'
          #      with_items: "{{ ssh_keys }}"


- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: "collect facts"
    setup:
    register: results

  - debug: var=results
